### ISSUE TITLE
LLJR

### ISSUE THREAD

**Issue by iaf22** [flyinactor91/AVWX-Engine#1]
any ICAO code starting with "LL" is = Israel
LLJR is not an exception.
See more at : https://en.wikipedia.org/wiki/Atarot_Airport

**Comment by flyinactor91** [comment]
I assume this is about LLJR and LLBS in the badStations.csv file. Let me explain why that exists.

I started with a comprehensive list of METAR reporting stations provided by NOAA ADDS at http://aviationweather.gov/docs/metar/stations.txt
This served as the master station list and has been updated over time as I cross-referenced a number of other databases to create stationList.csv with all of its additional information. However, when I started testing, I noticed that roughly 30% of those stations didn't return any data when queried. Any station that is listed in badStations.csv hasn't produced any data (according to the source, aviationweather.gov) since I started testing the pre-alpha version back in March 2015.

badStations.csv is more of a purgatory. Every couple of weeks, one of those stations will produce a report, which causes me to remove it from that list and update the server-side station database.
